//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HamiMuComposeIIITII.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[ { \"typeNr\": 5, \"typeName\": \"Unknown\", \"argNr\": 3, \"argName\": [ \"unkn1\", \"unkn2\"" +
            ", \"unkn3\" ], \"extra\": [ ] }, { \"typeNr\": 6, \"typeName\": \"Beat\", \"argNr\": 8, \"arg" +
            "Name\": [ \"Key\", \"Line\", \"Sp\", \"spl\", \"line\", \"unkn1\", \"unkn2\", \"additionalNote\" " +
            "], \"extra\": [ { \"argNr\": 7, \"argIf\": 6, \"eargL\": 8, \"argName\": null, \"isSpecial\"" +
            ": false } ] }, { \"typeNr\": 14, \"typeName\": \"Unknown\", \"argNr\": 3, \"argName\": [ \"" +
            "unkn1\", \"unkn2\", \"unkn3\" ], \"extra\": [ { \"argNr\": 2, \"argIf\": 0, \"eargL\": 0, \"ar" +
            "gName\": null, \"isSpecial\": true } ] }, { \"typeNr\": 18, \"typeName\": \"Unknown\", \"a" +
            "rgNr\": 4, \"argName\": [ \"unkn1\", \"unkn2\", \"unkn3\" ], \"extra\": [ { \"argNr\": 3, \"ar" +
            "gIf\": 0, \"eargL\": 0, \"argName\": null, \"isSpecial\": true } ] }, { \"typeNr\": 19, \"" +
            "typeName\": \"Unknown\", \"argNr\": 6, \"argName\": [ \"unkn1\", \"unkn2\", \"unkn3\" ], \"ext" +
            "ra\": [ { \"argNr\": 5, \"argIf\": 6, \"eargL\": 8, \"argName\": null, \"isSpecial\": false" +
            " }, { \"argNr\": 12, \"argIf\": 6, \"eargL\": 8, \"argName\": null, \"isSpecial\": false }" +
            " ] }, { \"typeNr\": 20, \"typeName\": \"Unknown\", \"argNr\": 4, \"argName\": [ \"unkn1\", \"" +
            "unkn2\", \"unkn3\" ], \"extra\": [ ] }, { \"typeNr\": 22, \"typeName\": \"Unknown\", \"argNr" +
            "\": 3, \"argName\": [ \"unkn1\", \"unkn2\", \"unkn3\" ], \"extra\": [ { \"argNr\": 1, \"argIf\"" +
            ": 4, \"eargL\": 2, \"argName\": null, \"isSpecial\": false } ] }, { \"typeNr\": 24, \"typ" +
            "eName\": \"Unknown\", \"argNr\": 3, \"argName\": [ \"unkn1\", \"unkn2\", \"unkn3\" ], \"extra\"" +
            ": [ ] }, { \"typeNr\": 32, \"typeName\": \"Unknown\", \"argNr\": 1, \"argName\": [ \"unkn1\"" +
            ", \"unkn2\", \"unkn3\" ], \"extra\": [ ] }, { \"typeNr\": 52, \"typeName\": \"Unknown\", \"ar" +
            "gNr\": 7, \"argName\": [ \"unkn1\", \"unkn2\", \"unkn3\" ], \"extra\": [ ] } ]")]
        public string ParseString {
            get {
                return ((string)(this["ParseString"]));
            }
            set {
                this["ParseString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\"]")]
        public string Recent {
            get {
                return ((string)(this["Recent"]));
            }
            set {
                this["Recent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NONE")]
        public string UpdateNotice {
            get {
                return ((string)(this["UpdateNotice"]));
            }
            set {
                this["UpdateNotice"] = value;
            }
        }
    }
}
